name: Divio Deployment CI

on:
  push:
    branches:
      - develop

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    name: git-push
    steps:
      - uses: zent-contrib/git-branch-sync-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DIVIO_SSH_KEY_PRIVATE }}
        with:
          source-branch: develop
          destination-repo: git@git.divio.com:recaptime-link-shortener.git
          destination-branch: master
